demo/UserMember/urls.py
from django.urls import path
from . import views
app_name = 'UserMember'

urlpatterns = [
    path('register/', views.registerUser.as_view(), name = 'registerUser'),
    path('login/', views.loginUser.as_view(), name = 'loginUser'),
    path('logout/', views.logoutUser, name = 'logout'),
]

demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home
from books import views as books
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.get_home),
    path('library/<int:id>/', books.get_books),
    path('addBookForm/', books.get_book_form),
    path('addBook/', books.add_book),
    path('', include('UserMember.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.site_header = "VNCert"

demo/UserMember/models.py
from django.db import models

# Create your models here.

demo/books/models.py
from django.db import models
from home.models import library
# Create your models here.
class books(models.Model):
    book_id = models.AutoField(primary_key=True)
    library_id = models.ForeignKey(library, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=False)
    age = models.IntegerField(null=True)
    bookfile = models.FileField(upload_to='files', null=False, default=None)

    def __str__(self):
        return f"{self.book_id}, {self.library_id}, {self.name}, {self.age}, {self.bookfile}"

demo/home/models.py
from django.db import models

# Create your models here.
class library(models.Model):
    library_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, null=False)

    def __str__(self):
        return f"{self.library_id}, {self.name}"

demo/UserMember/forms.py
from django import forms

class registerForm(forms.Form):
        username = forms.CharField(max_length=20)
        email = forms.EmailField()
        password = forms.CharField(max_length=20, widget=forms.PasswordInput)

class loginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput)

demo/UserMember/views.py
from dbm.ndbm import library
from django.shortcuts import render
from .forms import registerForm, loginForm
from django.views import View
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
class registerUser(View):
    def get(self, request):
        rF = registerForm
        return render(request, 'UserMember/register.html', {'rF' : rF})
    def post(self, request):
        lF = loginForm
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        user = User.objects.create_user(username, email, password)
        user.save()
        return render(request, 'UserMember/login.html', {'lF' : lF})

class loginUser(View):
    def get(self, request):
        lF = loginForm
        return render(request, 'UserMember/login.html', {'lF' : lF})
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return render(request, 'Templates/home.html')
        else:
            return HttpResponse('Login Fail')
  

def logoutUser(request):
    logout(request)
    return HttpResponse('Đã đăng xuất')

demo/books/views.py
from django.shortcuts import render, redirect
from .models import books as book_model
from home.models import library as library_model

# Create your views here.
def get_books(request, id):
    book_list = book_model.objects.filter(library_id = id)
    library = library_model.objects.get(library_id = id)
    return render(request, 'books.html', {'book_list' : book_list, 'library' : library})

def get_book_form(request):
    library_list = library_model.objects.filter()
    return render(request, 'bookForm.html', {'library_list' : library_list})

def add_book(request):
    if request.method == 'POST':
        library_id = request.POST['library']
        name = request.POST['fullName']
        age = request.POST['age']
        bookfile = request.FILES['bookfile']

        library = library_model.objects.get(library_id = library_id)

        book = book_model.objects.create(library_id = library, name = name, age = age, bookfile = bookfile)
        book.save()
        return redirect('/library/' + str(library_id))
    else:
        return render(request, 'error.html')

demo/home/views.py
from django.shortcuts import render
from .models import library as library_model
# Create your views here.
def get_home(request):
    library_list = library_model.objects.filter().order_by('library_id')
    return render(request, 'home.html', {'library_list' : library_list})

demo/UserMember/templates/UserMember/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<style>
    form{
        border-top: 10px solid darkgray;
        border-left: 10px solid darkgray;
        margin: 15% 40%;
        width: 300px;
        height: 100px;
        background-color: darkgray;
    }
</style>

<body>
    <form action="{% url 'UserMember:loginUser' %}" method="post">
        {% csrf_token %}
        {{lF.as_p}}
        <input type="submit">
    </form>
</body>
</html>

demo/UserMember/templates/UserMember/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <form style="margin: 15% 40%" action="{% url 'UserMember:registerUser' %}" method="post">
        {% csrf_token %}
        {{rF.as_p}}
        <input type="submit">
    </form>
</body>
</html> 